config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books do
    resources :orders, only: [:create]
    collection do
      get 'results', to: "books#results"
    end
  end
  resources :orders, only: [:destroy]
  resources :users, only: [:show, :edit]
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  validates :title, :price, :category, presence: true
  has_attachment :photo
   default_scope { order(created_at: :desc) }
  def self.search(search)
    where("title ILIKE ? OR author ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_attachments :photos, maximum: 3
  validates :start_time, :end_time, presence: true
  validates_uniqueness_of :user_id,  scope: :book_id
  default_scope { order(start_time: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :orders
  has_attachment :avatar, accept: [:jpg, :png, :gif]
  has_attachment :attachment
  validates :first_name, :last_name, presence: true
  geocoded_by :pickup_address
  after_validation :geocode, if: :pickup_address_changed?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  ## forcing to sign-up or sign-in otherwise you can't access it
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:attachment])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :results]
  ## it skips the sign-in action only for index and show pages
  def show
    #THE FORM FOR THE NEW ORDER IS ON THE SHOW PAGE OF THE BOOK
    @order = Order.new()
    @user=@book.user
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def index
    @books = Book.all
    @users = User.all
    if params[:title]
      redirect_to results_books_path
    end
  end

  def new
    @book = Book.new()
  end

  def create
    @book = Book.create(book_params)
    @book.user = current_user
    if @book.save
      redirect_to books_path
    else
      render :new
    end
    #SHOULD DO THE CONDITION WITH SAVE AND RENDER NEW
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to book_path
  end

  def destroy
    @book.destroy
    redirect_to(:back)
  end

  def results
    @books = Book.search(params[:title]).order("created_at DESC")
    @users = []
    @books.each do |book|
      @users << book.user
    end
    # @users = User.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@users.uniq) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :price, :category, :author, :photo)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @order = Order.new(order_params)
    @order.book = @book
    @order.user = current_user
    if book_is_available(@order.start_time, @order.end_time, @book) && current_user != @book.user
       @order.save
        redirect_to current_user
    else
      redirect_to book_path(@book)
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to(:back)
  end

  private

  def order_params
    params.require(:order).permit(:start_time, :end_time)
  end

  def book_is_available(start_time, end_time, book)
    orders = Order.where(book_id: book.id)
    date_range = start_time...end_time
    book_available = true
    orders.each do |order|
      if date_range.cover?(order.start_time) || date_range.cover?(order.end_time) || (order.start_time...order.end_time).cover?(@order.start_time) || (order.start_time...order.end_time).cover?(@order.end_time)
        return book_available = false
      break
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :order_with_user?
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @order = Order.new
  end


  def order_with_user?
    current_user.orders.each do |order|
      if order.book.user == @user
        return true
        break
      else
        return false
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div class="container margin-top">

<%= simple_form_for [@book] do |f| %>
<%= f.input :title %>
<%= f.input :author, as: :string %>
<%= f.input :price, as: :string %>
<%= f.input :description, as: :string %>
<%= f.input :category, as: :string %>
<%= f.input :photo, as: :attachinary %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

</div>

app/views/books/index.html.erb
<div class="container margin-top">

<div class="flexbox-harbor">
<div class="title-description">
<span> SET SAIL ON <br>A NEW STORY </span>
</div>

<div  class="books-harbor">
 <span class="blue">BOOKS</span> <br> HARBOR
</div>
</div>

 <div class="row">
    <% if user_signed_in? && !current_user.books.empty? %>
  <h3 class = "index-title"><span class="blue"> MY </span>  COLLECTION</h3>
      <% current_user.books.each do |book| %>
        <div class="col-xs-12 col-sm-6 col-md-4 padded">
          <div class="card">
            <div class = "card-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path book.photo.path %>');" > </div>
              <div class="book-content">
              <h3 class="book-title"> <%= truncate(book.title, length: 25, separator: " ", omission: " ...") %> </h3>
                <div class="book-description"> <%= truncate(book.description, length: 100) %></div>
              </div>
              <h3 class = "book-price"> <%= book.price %> $ | week </h3>
              <span class = "book-category" id= "on-small-card"> <%= book.category.upcase %> </span>
              <li> <%= link_to 'show', book_path(book) %> </li>
              <%= link_to '', book_path(book), class: 'card-link' %>
            </div>
          </div>
      <% end %>
    <% end %>
   </div>

<div class="row">
<h3 class = "index-title"><span class="blue"> NEW </span> ARRIVALS</h3>
  <% @books.each do |book| %>
  <div class="col-xs-12 col-sm-6 col-md-4 padded">
    <div class="card">
      <div class = "card-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path book.photo.path %>');" > </div>


        <div class="book-content">
        <h3 class="book-title"> <%= truncate(book.title, length: 25, separator: " ", omission: " ...") %> </h3>
          <div class="book-description"> <%= truncate(book.description, length: 100)%></div>
        </div>
        <h3 class = "book-price"> <%= book.price %> $ | week </h3>
        <span class="book-category" id="on-small-card" > <%= book.category.upcase %> </span>
        <li> <%= link_to 'show', book_path(book) %> </li>
        <%= link_to '', book_path(book), class: 'card-link' %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/books/new.html.erb
<div class="container margin-top">
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
<%= simple_form_for [@book] do |f| %>
<%= f.input :title, placeholder: 'Moby Dick' %>
<%= f.input :author, as: :string, placeholder: 'Herman Melville'%>
<%= f.input :price, as: :string ,label: 'Price per week', placeholder: 'Your price per week'%>
<%= f.input :description, as: :text, placeholder: 'Moby-Dick or, The Whale is a novel published in 1851 during the period of the American Renaissance..'%>
<%= f.input :category, as: :string, placeholder: 'Novel /  ‎Adventure fiction‎'%>
<%= f.input :photo, as: :attachinary %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>
</div>
</div>
</div>

app/views/books/results.html.erb
<div class="container margin-top for-map">
<div class="row ">
  <h3 class = "index-title"><span class="blue"> </span> RESULTS </h3>
    <% @books.each do |book| %>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 padded">
      <div class="card">
        <div class = "card-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path book.photo.path %>');" > </div>

        <div class="book-content">
        <h3 class="book-title"> <%=book.title%> </h3>
          <div class="book-description"> <%= truncate(book.description, length: 100) %></div>
        </div>
        <h3 class = "book-price"> <%= book.price %> $ </h3>
        <span class = "book-category" id="on-small-card"> <%= book.category.upcase %> </span>
        <li> <%= link_to 'show', book_path(book) %> </li>
        <%= link_to '', book_path(book), class: 'card-link' %>
      </div>
    </div>
    <% end %>
</div>

<% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      });
    <% end %>
  <% end %>



<div class="map-position" id="map" ></div>

app/views/books/show.html.erb
<div class="margin-top">
<div class="banner-show">

  <div class = "banner-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path @book.photo.path %>');" >

   <div class = "avatar-user">
    <a href="/users/<%= @book.user.id %>" >
      <% avatar_url = @book.user.facebook_picture_url || cl_image_path(@book.user.attachment.path) || "http://placehold.it/30x30" %>
      <%= image_tag avatar_url, class: 'avatar-large'%>
    </a>
  </div>
  </div>


  <div class="banner-description">
   <div class="flexbox-title">
    <h3 class="book-title"> <%= @book.title%> <p id="author"> <i> by <%= @book.author %> </i></p> </h3>
  </div>


  <div class="book-full-description"> <%= @book.description %></div>

 <div >
   <%= simple_form_for [@book, @order], html: {class: "flexbox-order-form"} do |f| %>
   <%= f.input :start_time, as: :string, label: "From:",placeholder: 'start-date', input_html: { class: 'datepicker'}, wrapper_html: {class: 'smaller'} %>
   <%= f.input :end_time, as: :string, label: "to:",placeholder: 'end-date', input_html: { class: 'datepicker'}, wrapper_html: {class: 'smaller'}%>
   <%= f.button :submit, class: 'btn btn-order' %>
   <% end %>
 </div>

  <h3 id="price" class = "book-price bigger"> <%= @book.price %> $ | week</h3>

  <div class = "list-of-dates">
<% unless @book.orders.empty?%>
  <h4> <i class="fa fa-calendar" aria-hidden="true"> </i> Calendar </h4>
<% end %>
      <% @book.orders.each do |order| %>
      <a href="/users/<%= order.user.id %>" class="profile-link" > <div class="date-element"> <%= order.user.first_name%> : <%= order.start_time %> | <%= order.end_time %>  </div> </a>
      <% end %>
    </div>

<% unless @book.user.pickup_address.nil? %>
<div class="map-book" id="map" ></div>
<% end %>

</div>

<!-- CATEGORIES IN FLEXBOX AT BOTTOM  -->
<div class="flexbox-categories">
  <span class = "book-category" id="on-big-card"> <%= @book.category.upcase %> </span>
</div>
<!-- -------------- -->


</div>

<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).ready(function() {
$('.datepicker').datepicker();
});
<% end %>
<% end %>
</div>

<div class="go-back">
   <%= link_to root_path do %><h3>  < BACK </h3><% end %>
</div>




<% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
           handler.getMap().setZoom(14);
        });
      });
    <% end %>
  <% end %>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible under-navbar" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible under-navbar" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->

    <div class="navbar-form navbar-left">
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "harbor.png" %>
      <% end %>

      <%= form_tag(results_books_path, :method => "get", id: "search-form", class: "navbar-wagon-search" ) do %>
      <%= text_field_tag :title, params[:title], placeholder: "Search Title or Author", class: "navbar-wagon-search-input" %>
      <%= submit_tag "Search", :style => "display: none;", :name => nil %>
      <% end %>
    </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Different navigation if login or not -->
    <%= link_to "LEND YOUR BOOK!", new_book_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || cl_image_path(current_user.attachment.path) || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "My Harbor") %>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Books-Harbor</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico'  %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,700" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flashes' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="container margin-top">

  <div class="text-center marginbot">
    <div class="row">
      <%# if !@user.Attachment.empty? %>
        <% avatar_url = @user.facebook_picture_url  || cl_image_path(@user.attachment.path) || "http://placehold.it/30x30" %>

        <div class = "profile-pic" style="background-image: url('<%= avatar_url %>');" >
<% if @user.id == current_user.id %>
   <%= link_to '', edit_user_registration_path, class: "fa fa-pencil cross" %>
<% end %>


        <!-- <%= image_tag avatar_url, class: "profile-pic" %> -->
      <%# avatar_url = @user.facebook_picture_url || "http://placehold.it/30x30" %>

      </div>
    </div>
    <div class="row">
      <h2 class="profile-name"><%= @user.first_name.upcase %> <%= @user.last_name.upcase %></h2>
<% if order_with_user? %>
      <h4><%= @user.email %></h4>
<% end %>
    </div>
  </div>

  <div class="row my-collection">
    <% if user_signed_in? && !@user.books.empty? %>
    <h3 class = "index-title">
    <% if @user.id == current_user.id %>
   <span class="blue">YOUR
<% else %>
<span class="blue"> <%= @user.first_name.upcase %>' S
<% end %>
 </span> COLLECTION</h3></h3>
    <% @user.books.each do |book| %>
    <div class="col-xs-12 col-sm-6 col-md-4 padded">
      <div class="card profile-page">
        <div class = "card-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path book.photo.path %>');" > </div>
        <div class="book-content">
          <h3 class="book-title"> <%= book.title%> </h3>
          <div class="book-description"> <%= truncate(book.description, length: 125) %></div>
        </div>
        <h3 class = "book-price"> <%= book.price %> $ </h3>
        <span class = "book-category" id= "on-small-card"> <%= book.category.upcase %> </span>
        <% if @user.id == current_user.id %>
      <%= link_to '', book, method: :delete, class: 'fa fa-times cross' %>
<% end %>
        <li> <%= link_to 'show', book_path(book) %> </li>
        <%= link_to '', book_path(book), class: 'card-link' %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>



  <div class="row">
   <h3 class="index-title">
   <% unless @user.orders.empty? %>
 <% if @user.id == current_user.id %>
   <span class="blue">YOUR
<% else %>
<span class="blue"> <%= @user.first_name.upcase %>' S
<% end %>
 </span> NEXT LECTURES</h3>
<% end %>
   <% @user.orders.each do |order| %>

   <div class="col-xs-12 col-sm-6 col-md-4 padded">
   <div class="card profile-page">
      <div class = "card-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path order.book.photo.path %>');" > </div>
      <div class="dates"> <%= order.start_time %> -- <%= order.end_time %></div>
<% if @user.id == current_user.id %>
      <%= link_to '', order, method: :delete, class: 'fa fa-times cross' %>
<% end %>
      <div class="book-content">
        <h3 class="book-title"> <%=truncate(order.book.title, length: 25, separator: " ", omission: " ..." )%> </h3>
        <div class="book-description"> <%= truncate(order.book.description, length: 125) %></div>
      </div>
      <h3 class = "book-price"> <%= order.book.price %> $ | week</h3>
      <span class = "book-category" id="on-small-card"> <%= order.book.category.upcase %> </span>
      <li> <%= link_to 'show', book_path(order.book) %> </li>
      <%= link_to '', book_path(order.book), class: 'card-link' %>
    </div>
  </div>
  <% end %>
</div>



<div class="go-back user-back">
   <%= link_to :back do %><h3>  < BACK </h3><% end %>
</div>